version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      # if your app needs to run on a subpath, place it here - e.g. /timekpr
      SCRIPT_NAME: /
